### ISSUE TITLE
Issue google search 

### ISSUE THREAD

**Issue by tanyafilo** [gis-ops/routing-py#16]
Hey, may you help me with my own issue? 
I'm trying to scrape large amount of results in Google, but I reach a limit of XXX with the message :

"In order to show you the most relevant results, we have omitted some entries very similar to the XXX already displayed.
If you like, you can repeat the search with the omitted results included."

I'm trying to get through 1000 results.
Any advises? clues? 
Thanks ahead.

**Comment by nilsnolde** [comment]
No idea. You'd need to provide some more information, I have literally no idea what you're trying to do.. 

Are you even using routing-py for this? Endpoint? Example request?

**Comment by nilsnolde** [comment]
Closing as invalid for now.. Feel free to provide more info and re-open if relevant
