### ISSUE TITLE
Faulty geometries returned by HereMaps.isochrones()

### ISSUE THREAD

**Issue by chrstnbwnkl** [gis-ops/routing-py#29]
#### Here's what I did

Wanted to calculate isochrones with HereMaps:

```python
api = get_router_by_name("heremaps")(api_key="tm04dMxnZ5rRKQVxfvGTtgkpV3FEerIDoExbDG0kEPs")

location = [13.410701945045075, 52.56057471477219]

isochrones = api.isochrones(locations=location, profile="car", intervals=[300,600])
```

---
#### Here's what I got

* An `Isochrones` object with geometries consisting of list of `list_reverseiterator`s
---
#### Here's what I was expecting

* An `Isochrones` object with geometries consisting of lists of coordinates
---
#### Here's what I think could be improved

* when parsing the result returned by the API, make sure to convert the reversed coordinates to a list on line 1094

**Comment by nilsnolde** [comment]
fixed in #31
