### ISSUE TITLE
OSRM route returns sparse coordinates compared to ORS

### ISSUE THREAD

**Issue by vutle** [gis-ops/routing-py#36]
For the same route, I found that OSRM returns less coordinates compared to ORS.  Is there a setting to make OSRM return all points?

OSRM offline
![image](https://user-images.githubusercontent.com/6241928/124002107-b3782d80-da18-11eb-972a-fa9b4ed96c26.png)

ORS offline
![image](https://user-images.githubusercontent.com/6241928/124002241-d73b7380-da18-11eb-8b78-317e748077f3.png)

**Comment by nilsnolde** [comment]
For help with individual routing engines, please see their documentation to understand what's possible:
http://project-osrm.org/docs/v5.5.1/api/#route-service

Also all the methods have docstrings in routing-py which tell you very conveniently what the router's parameters are doing (although the description for `overview` is pretty poor):
https://routingpy.readthedocs.io/en/latest/?badge=latest#routingpy.routers.OSRM.directions

**Comment by vutle** [comment]
Thanks.  I found that you need to set it to full.
overview = "full"
