### ISSUE TITLE
GraphHopper parsing fails with not encoded points

### ISSUE THREAD

**Issue by schaemar** [gis-ops/routing-py#54]
#### Here's what I did

I set points_encoded=False to verify that during parsing of points in GraphHopper response are always decoded as polyline even if points_encoded=False 
```
url:
http://localhost:8989/route?vehicle=car&point=50.046531%2C14.514527&point=50.068452%2C14.508087&points_encoded=false&debug=true
Parameters:
{
  "headers": {
    "User-Agent": "routingpy/v0.3.3",
    "Content-Type": "application/json"
  },
  "timeout": 60
}
```
---
#### Here's what I got

Key error from _trans / _decode

---
#### Here's what I was expecting

Geometry should be parsed from the JSON LineString

---
#### Here's what I think could be improved

Decoding from polyline should not happen if the response contains `points_encoded=False`

**Comment by nilsnolde** [comment]
yeah right.. it always tries to decode the points. will fix. thanks for the hint!
