### ISSUE TITLE
pypi release

### ISSUE THREAD

**Issue by nurikk** [gis-ops/routing-py#69]
Hello, would it be possible to release recent changes to pypi? Especially [this one ](https://github.com/gis-ops/routing-py/commit/0a22e110edfce9dd06141b9de976bfb6a06a9015) since it changed url (removed profile and added `driving`) it fails tests

**Comment by nilsnolde** [comment]
yeah you're right. we just released 1.0.0, was about time: https://pypi.org/project/routingpy/
