### ISSUE TITLE
Incorrect use of `unit_factor`?

### ISSUE THREAD

**Issue by chrstnbwnkl** [gis-ops/routing-py#77]
1. This should be used for distances, not duration, right?
    https://github.com/gis-ops/routing-py/blob/cfae3c97fbdb2b7ac1dc2379e409b81c64d1c57b/routingpy/routers/openrouteservice.py#L361

2. Conversion is missing here
    https://github.com/gis-ops/routing-py/blob/cfae3c97fbdb2b7ac1dc2379e409b81c64d1c57b/routingpy/routers/openrouteservice.py#L348

**Comment by nilsnolde** [comment]
jep oops, thanks for spotting!
